#!/usr/bin/env python3
"""
extract-binaries.py — Bootstrap a coverage check from an existing settings.json.

Part of the command-autoapprove-onboarding skill.
See ../SKILL.md §4b Step B1 (alternative input source).

Walks every key in chat.tools.terminal.autoApprove, strips anchors and JSON
escapes, splits on pipelines / chains, and emits one representative invocation
per distinct binary on stdout. The output is ready to pipe straight into
batch-coverage-check.py via `--commands /dev/stdin` (or a tempfile).

Usage:
    python3 extract-binaries.py --settings <path/to/settings.json>
    python3 extract-binaries.py --settings <path> --out /tmp/cmds.txt

Exit codes:
    0  success    1  file/parse error
"""

import argparse
import json
import re
import sys

# Tokens to ignore when scanning for the first "command" of a segment.
_NOISE = {
    "if", "else", "elseif", "foreach", "for", "while", "do", "switch",
    "function", "param", "try", "catch", "finally", "return", "break",
    "continue", "begin", "process", "end", "in", "and", "or", "not",
    "true", "false", "null",
}

# Regex to match a PowerShell verb-noun cmdlet at the start of a segment.
_PS_CMDLET = re.compile(r"^([A-Z][a-z]+-[A-Za-z]+)\b")
# Regex for typical unix-style binaries.
_UNIX_BIN = re.compile(r"^([a-z][a-z0-9_+.-]*)\b")
# git subcommand picker (after stripping optional -C <path>).
_GIT_SUB = re.compile(
    r"^git(?:\s+-C\s+(?:\"[^\"]*\"|\S+))?\s+([a-z][a-z0-9-]*(?:\s+[a-z][a-z0-9-]*)?)"
)


def unescape_key(key: str) -> str:
    """Strip /^…$/ anchors and decode common JSON escapes back to source form."""
    body = key
    if body.startswith("/^") and body.endswith("$/"):
        body = body[2:-2]
    # Reverse double-escaped backslashes used inside JSON regex keys.
    body = body.replace(r"\\\\", "\\").replace(r"\\.", ".")
    # Strip regex escapes for shell-meta we care about.
    for esc, lit in [
        (r"\$", "$"), (r"\(", "("), (r"\)", ")"), (r"\{", "{"), (r"\}", "}"),
        (r"\[", "["), (r"\]", "]"), (r"\|", "|"), (r"\.", "."),
    ]:
        body = body.replace(esc, lit)
    return body


def split_segments(body: str) -> list[str]:
    """Split on shell pipeline / chain separators.

    Best-effort: a regex body may contain unescaped alternation `|` inside a
    group (e.g., `( -v| show)?`) that mimics a pipeline. We split anyway and
    rely on the caller (and the downstream `batch-coverage-check.py` review)
    to discard phantom binaries that surface from regex syntax. The output is
    intended for human review before feeding into onboarding.
    """
    parts = re.split(r"\s*(?:\||&&|\|\|\||;|\n)\s*", body)
    return [p.strip() for p in parts if p.strip()]


def first_binary(segment: str) -> str | None:
    """Return the leading command/binary token of a segment, or None."""
    s = segment.lstrip()
    # Strip leading variable assignment like `$x = ...`
    s = re.sub(r"^\$[A-Za-z_][A-Za-z0-9_]*\s*=\s*", "", s)
    if not s:
        return None
    m = _GIT_SUB.match(s)
    if m:
        sub = m.group(1).split()
        # Compound subcommands (e.g., "stash show") get the first two tokens.
        return f"git {sub[0]}" if len(sub) == 1 else f"git {sub[0]} {sub[1]}"
    m = _PS_CMDLET.match(s)
    if m:
        return m.group(1)
    m = _UNIX_BIN.match(s)
    if m and m.group(1) not in _NOISE:
        return m.group(1)
    return None


def canonical_invocation(binary: str) -> str:
    """Build a representative invocation line for the binary."""
    if binary.startswith("git "):
        # e.g., 'git stash show' -> 'git stash show stash@{0}'
        return f'{binary} <args>'
    if "-" in binary and binary[0].isupper():
        # PowerShell cmdlet
        return f'{binary} <args>'
    return f'{binary} <args>'


def main() -> int:
    ap = argparse.ArgumentParser(description="Extract distinct binaries from autoApprove.")
    ap.add_argument("--settings", required=True, help="Path to VS Code settings.json")
    ap.add_argument("--out", help="Output file (default: stdout)")
    args = ap.parse_args()

    try:
        data = json.load(open(args.settings, encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"ERROR: cannot read {args.settings}: {e}", file=sys.stderr)
        return 1

    aa = data.get("chat.tools.terminal.autoApprove", {})
    binaries: set[str] = set()
    for key in aa:
        body = unescape_key(key) if key.startswith("/") else key
        for seg in split_segments(body):
            b = first_binary(seg)
            if b:
                binaries.add(b)

    lines = [
        "# Auto-generated by extract-binaries.py from existing autoApprove entries.",
        "# Feed into batch-coverage-check.py via --commands.",
        "",
    ]
    lines.extend(canonical_invocation(b) for b in sorted(binaries))

    out = "\n".join(lines) + "\n"
    if args.out:
        open(args.out, "w", encoding="utf-8").write(out)
        print(f"Wrote {len(binaries)} distinct binaries to {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
